name: Tests

on: [pull_request]

env:
  CI: true

jobs:
  "ğŸ— Build":
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build
        run: "npm run build"

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
          retention-days: 1

  "ğŸ§ª Lint":
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run linting
      run: 'npm run test:lint'

  "ğŸ§ª Unit":
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run unit tests
      run: 'npm run test:unit'

  "ğŸ§ª E2E":
    runs-on: ubuntu-latest

    needs: build

    env:
      TESTCAFE_BROWSER: 'chrome:headless'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: dist

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run e2e tests
      run: 'npm run test:e2e'

    - name: Archive allure reporter output
      uses: actions/upload-artifact@v2
      with:
        name: allure
        path: allure
        retention-days: 1

  "ğŸ§ª Integration":
    runs-on: ubuntu-latest

    needs: e2e

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: allure
        path: allure

    - name: Run integration tests
      run: 'npm run test:integration'
